### ISSUE TITLE
last_index_before

### ISSUE THREAD

**Issue by mwappner** [neurophysik/CHSPy#2]
In a `CubicHermiteSpline`, if `t0` is the time of one of the anchors should `CubicHermiteSpline.last_index_before(t0)` return the index of that anchor or the one before `t0`? I'd argue the former, the current behavior is the latter.

Minimal example, following from the docs' example:

```python
from chspy import CubicHermiteSpline
spline = CubicHermiteSpline(n=3)

#            time   state    slope
spline.add((   0 , [1,3,0], [0,1,0] ))
spline.add((   1 , [3,2,0], [0,4,0] ))
spline.add((   4 , [0,1,3], [0,4,0] ))

spline.last_index_before(4) # >> 1
```
my argument here being this should return 2. Granted, if you _know_ your queried time is one of the anchors, you can just add one to the results, but if you _don't_ know, it's more bothersome to check. The proposed change can be added by just  replacing `bisect_left` with `bisect` in (this line)[https://github.com/neurophysik/CHSPy/blob/94fff4dc5f7bc1fb50b4e5b8d2d9c590a4fb641e/chspy/_chspy.py#L425].

An argument could be made for the current functionality given the name of the function: if `t0` is an anchor, then you can't return the index that has `t0` if the user is querying for the one before it. In that case, an alternative solution would be to add a function to cheaply check `t0 in spline.times` that doesn't involve (calculating the times every time)[https://github.com/neurophysik/CHSPy/blob/94fff4dc5f7bc1fb50b4e5b8d2d9c590a4fb641e/chspy/_chspy.py#L418]. If the list of times were to be saved in the instance instead of calculated every time it would become reasonable to do

```python
if t0 in ts := spline.times:
   index = ts.index(t0)
else:
   index = spline.last_index_before(t0)
```

or alternatively

```python
index = spline.last_index_before(t0)
if t0 in splines.time:
    index += 1
```

both these approaches would benefit from `CubicHermiteSpline.times` not being calculated when queried.

**Comment by Wrzlprmft** [comment]
* The behaviour of `last_index_before` you describe is as intended and what its name describes. This behaviour may seem a bit weird at first glance, but it is that way because for some applications (within CHSPy and JiTCDDE) this is the most convenient behaviour. In most cases the behaviour doesn’t make a difference, because evaluating either segment of the spline at the anchor returns the same result. Otherwise, this ensures an easy and consistent behaviour if you happen to be at the beginning or end of the spline. The idea is roughly that if `i=spline.last_anchor_before(t)`, then `spline[i]` and `spline[i+1]` are the right anchors to use to evaluate at `t`, as long as `t` is before the last anchor.

* I won’t introduce a backwards-incompatible change here, but if you have some application for a function that works differently, it should be no problem to implement it. However, due to the above, I am somewhat skeptical that this is really the case.

* CHSPy is not really made for efficiency in every concern, in particular when it comes to many anchors.

**Comment by mwappner** [comment]
Following your bullet points:
1. I see what you mean, I'm not gonna push in that direction anymore. It makes sense in the context you present it.
2. The function I'd suggest would be something like `first_index_after` which would be a clone of `last_index_before` but use `bisect` instead of `bisect_left`. However, I do agree there's no need to bloat the method space of the class for such a tiny functionality change, so i wouldn't expect it to be added.
3. I understand that. All I'd ask is for the class to store a copy of `self.t` instead of generating it on the fly every time. Maybe to avoid an overhead when adding new anchors, generate the time vector when queried the first time and save it for future queries. Something along the lines of
```python
	@property
	def times(self):
		"""
		The times of all anchors.
		"""
                if self._times_needs_update:
            	      self._times = [anchor.time for anchor in self]
                return self._times
```
And then keep track of when `_times` has to be updated (when the instance is first created or adding or deleting anchors, essentially). This would result in a very low overhead way to keep track of the times vector without having to iterate over all anchors each time it's queried. And as outlined in my first post, this would also pretty much void the need for the function I  suggest in 2.

**Comment by Wrzlprmft** [comment]
Here you go. Times are now stored and updated on demand. And you have `first_index_after`, which works exactly as it says on the tin, i.e., with a strict _after._

**Comment by Firigion** [comment]
Oman, I wasn't expecting you to add them, this looks good. Thanks!

**Comment by mwappner** [comment]
Oman, I wasn't expecting you to add them, this looks good. Thanks!

PS: posted earlier with the wrong account
